config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  
  # Authentication
  devise_for :users

  # Blog
  get 'blogs/new', to: 'blog#new'
  post 'blogs', to: 'blog#create'

  # Posts
  get '/:slug', to: 'posts#index', as: 'posts'
  get '/:slug/rss', to: 'posts#feed', as: 'posts_rss'

  get 'blogs/:slug/posts/new', to: 'posts#new', as: 'new_post'
  post 'blogs/:slug/posts', to: 'posts#create', as: 'create_post'
  
  get '/:slug/:id', to: 'posts#edit', as: 'edit_post'
  patch '/:slug/:id', to: 'posts#update', as: 'update_post'

  delete '/:slug/:id', to: 'posts#destroy', as: 'delete_post'

  # Comments
  get '/:slug/:id/comments', to: 'comments#index', as: 'comments'
  get '/:slug/:id/comments', to: 'comments#new', as: 'new_comments'
  post '/:slug/:id/comments', to: 'comments#create', as: 'create_comments'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	before_save :sanitize_url_slug

	validates :name, :url_slug, presence: true
	has_many :posts, dependent: :destroy
	belongs_to :user
	has_attached_file :cover_image, styles: {medium: "200x200", large: "1140x296"}
	validates_attachment_content_type :cover_image,
									 :content_type => ["image/jpg", "image/jpeg", "image/png"]


	scope :find_by_slug, ->(slug) {find_by(url_slug: slug)}


	def sanitize_url_slug
		self.url_slug.gsub!(/[^a-zA-Z0-9\-]/,"")
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :text, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base

	validates :title, presence: true
	
	belongs_to :blog
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :blogs


  def gravatar size
  	gravatar_hash = Digest::MD5.hexdigest(self.email.downcase)
  	"https://www.gravatar.com/avatar/#{gravatar_hash}.jpg?s=#{size}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
	before_action :authenticate_user!

	def new
		@blog = Blog.new
	end

	def create
		@blog = current_user.blogs.build(blog_params)

		if @blog.save
			redirect_to root_path, notice: "A new blog has been created."
		else
			render :new
		end

	end


	private
		def blog_params
			params.require(:blog).permit(:name, :url_slug, :cover_image)
		end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :get_blog_post_comments, only: [:index, :create]

def index
	@comments = @post.comments
end

def new
	@comment = Comment.new
end

def create
	@comment = @post.comments.build(permit_params)
	if @comment.save
		redirect_to comments_path(@blog.url_slug, params[:id]), notice: "Your comments has be posted successfully."
	else
		redirect_to comments_path(@blog.url_slug, params[:id]), flash: { error: "Cannot enter blank comment." }
	end
end


private
	
	def permit_params
		params.require(:comment).permit(:text)	
	end

	def get_blog_post_comments
		@blog = Blog.find_by_slug params[:slug]
		@post = @blog.posts.includes(:comments).find_by(id: params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@blogs = Blog.order('id desc')
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
	before_action :get_blog_and_posts_from_slug, only: [:index, :create, :update, :edit, :destroy]

	def new
		@post = Post.new
	end

	def create
		@post = @blog.posts.build(permit_params)
		if @post.save
			redirect_to posts_path(params[:slug]), notice: "Your post has been created successfully."
		else
			render :new
		end
	end

	def index
		@posts = @blog.posts.order('id desc')
		@redcarpet = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
		@user_have_access = @blog.user == current_user
		
		respond_to do |format|
			format.html
			format.rss { render layout: false }
		end
	end

	def edit
		
	end

	def update
		if @post.update(permit_params)
			redirect_to posts_path(params[:slug]), notice: "Your post has be updated successfully."
		else
			render :edit
		end
	end

	def destroy
		if @post.destroy
			redirect_to posts_path(params[:slug]), notice: "Your post has been deleted successfully."
		end
	end

	private
		def permit_params
			params.require(:post).permit(:title, :content)
		end

		def get_blog_and_posts_from_slug
			@blog = Blog.find_by_slug params[:slug]
			@post = @blog.posts.find_by(id: params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blog/new.html.erb
<%= simple_form_for @blog, url: blogs_path, html: {multipart: true} do |f| %>

	<div class="container">

		<div class="page-header">
			<h1>New Blog</h1>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<div class="form-group">
					<%= f.input :name %>
				</div>

				<div class="form-group">
					<%= f.input :url_slug %>
				</div>

				<div class="form-group">
					<%= f.input :cover_image %>
				</div>

				<div>
					<%= f.submit 'Create', class: 'btn btn-lg btn-primary',data: {disable_with: "Create..."} %>
				</div>
			</div>
		</div>

	</div>

<% end %>

app/views/comments/index.html.erb
<%= link_to "Posts", posts_path(@blog.url_slug) %>
<h1>Comments</h1>

<% @comments.each do |comment| %>

	<div class="well well-lg">
		<p>
			<%= comment.text %>
		</p>
	</div>

<% end %>

<h1>
	New Comment
</h1>
<%= simple_form_for :comment, url: create_comments_path do |f| %>
	
	<%= f.input :text, as: :text, required: true %>
	<%= f.submit "Submit", class: 'btn btn-lg btn-primary', data: {disable_with: "Submit..."} %>

<% end %>

app/views/home/index.html.erb
<div class="page-header">
	<div class="page-body">
		<div class="page-header">
			<h1>
				List of Blogs
			</h1>
			<p><%= link_to "Create Blog", blogs_new_path , class: "btn btn-primary btn-lg" %>
		</div>

			<ul class="list-group">
				<% @blogs.each do |blog| %>
					<li class="list-group-item">
						<h2>
							<%= link_to blog.name, posts_path(slug: blog.url_slug) %>
						</h2>
						<p>
							<b>Blogger: </b> <%= blog.url_slug %>
						</p>
					</li>
				<% end %>
			</ul>
		</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Blogr", root_path, class: "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if !user_signed_in? %>
        <li>
          <%= link_to 'Log In', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
      <% else %>
        <li>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>          
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Blogr</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

	<%= render 'layouts/header' %>
	<div class="container">
		
		<%= render 'layouts/flash/messages' %>

		
		<p class="alert">
			<%= alert %>
		</p>
		
		<%= yield %>
	</div>

	</body>
</html>

app/views/layouts/flash/_messages.html.erb
<% if flash[:notice] %>
	<div class="alert alert-info">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p> <%= flash[:notice] %> </p>
	</div>
<% end %>

<% if flash[:error] %>
	<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<p> <%= flash[:error] %> </p>
	</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= simple_form_for @post, url: update_post_path do |f| %>
	<div class="form-group">
		<%= f.input :title %>
		<%= f.input :content, as: :text %>
		<%= f.submit "Submit", class: 'btn btn-primary btn-lg', data: {disable_with: "Submit..."} %>
	</div>
<% end %>

app/views/posts/index.html.erb
<%= link_to 'Home', root_path %> 

<div class="jumbotron">
	<%= image_tag @blog.cover_image.url(:large) %>
</div>

<div class="row">
	<div class="col-md-10">
		<h1>
			<%= @blog.url_slug	%> posts
		</h1>
	</div>
	<div class="col-md-1">
		<% if @user_have_access %>
			<p>
				<%= link_to "New Post", new_post_path, class: 'btn btn-lg btn-primary' %>
			</p>
		<% end %>
	</div>
	<div class="col-md-1">
		<p>
			<%= link_to "RSS", posts_path(@blog.url_slug, {format: :rss}), class: 'btn btn-lg btn-primary' %>
		</p>
	</div>
</div>

<div>
	<% @posts.each do |post| %>
		<div class="well well-lg">
			<div class="row" id="<%= dom_id(post) %>" >
					<div class="col-md-2">
						<%= image_tag @blog.user.gravatar(100) %>
					</div>

					<div class="col-md-10">
						<h2>
							<%= link_to post.title, "#" %>
						</h2>
						<p>
							<%= @redcarpet.render(post.content).html_safe %>
						</p>
						<% if @user_have_access %>
							<%= link_to edit_post_path(@blog.url_slug, post.id), id: post.id do %>
								Edit
								<span class="glyphicon glyphicon-pencil space"></span>
							<% end %>
							<%= link_to delete_post_path(@blog.url_slug, post.id), method: :delete, 
								data: { confirm: 'Are you sure?' } do %>
								Delete
								<span class="glyphicon glyphicon-trash space"></span>
							<% end %>
						<% end %>
						<%= link_to comments_path(@blog.url_slug, post.id) do %>
							Comments
							<span class="glyphicon glyphicon-comment"></span>
						<% end %>
					</div>
			</div>
		</div>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= simple_form_for @post, url: create_post_path do |f| %>
	<div class="form-group">
		<%= f.input :title %>
		<%= f.input :content, as: :text %>
		<%= f.submit "Submit", class: 'btn btn-primary btn-lg', data: {disable_with: "Submit..."} %>
	</div>
<% end %>